/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_noveogroup_android_application_NativeLibrary */

#ifndef _Included_com_noveogroup_android_application_NativeLibrary
#define _Included_com_noveogroup_android_application_NativeLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_noveogroup_android_application_NativeLibrary
 * Method:    sum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_noveogroup_android_1application_NativeLibrary_sum
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_noveogroup_android_application_NativeLibrary
 * Method:    getUTF8String
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_noveogroup_android_1application_NativeLibrary_getUTF8String
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
